[package]
name="noodle_egui"
version="0.1.0"
edition="2021"
authors=["Veritius <veritiusgaming@gmail.com>"]
license="MIT OR Apache-2.0"
description="Egui integration for noodle"

[dependencies.noodle_core]
version = "0.1.0"
path = "../core"
features = ["std"]

[dependencies.egui]
version = "0.28"